<?php require __DIR__ . '/layout/header.phtml' ?>

<main class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="alert alert-danger" role="alert">
                <h4 class="alert-heading">Error</h4>
                <p><?= htmlspecialchars($mensaje ?? 'Se ha producido un error inesperado. Por favor, intente nuevamente.'); ?></p>
                <hr>
                <div class="">
                    <a href="login_form" class="btn btn-primary">Volver atrás</a>
                </div>
            </div>
        </div>
    </div>
</main>

<?php require __DIR__ . '/layout/footer.phtml' ?>