
<?php require_once __DIR__ . '/../layout/header.phtml'; ?>

    <h1><?= isset($interprete) ? 'Editar' : 'Agregar' ?> intérprete</h1>

    <a href="<?= BASE_URL ?>interprete">← Volver a intérpretes</a>

        <form method="POST" action="<?= BASE_URL ?><?= isset($interprete) ? 'editInterprete/' . $interprete->ID_Interprete : 'addInterprete' ?>">
        
        <label>Nombre:</label>
        <input type="text" name="Nombre" value="<?= isset($interprete) ? $interprete->Nombre : '' ?>">
        
        <label>Género:</label>
        <input type="text" name="Genero" value="<?= isset($interprete) ? $interprete->Genero : '' ?>">
        
        <label>Tipo:</label>
        <input type="text" name="Tipo" value="<?= isset($interprete) ? $interprete->Tipo : '' ?>">
        
        <label>País de origen:</label>
        <input type="text" name="Pais_Origen" value="<?= isset($interprete) ? $interprete->Pais_Origen : '' ?>">
        
        <label>Sello discográfico:</label>
        <input type="text" name="SelloDiscografico" value="<?= isset($interprete) ? $interprete->SelloDiscografico : '' ?>">
        
        <label>Sitio web:</label>
        <input type="text" name="SitioWeb" value="<?= isset($interprete) ? $interprete->SitioWeb : '' ?>">
        
        <label>Fecha de inicio:</label>
        <input type="date" name="FechaInicio" value="<?= isset($interprete) ? $interprete->FechaInicio : '' ?>">
        
        <label>Imagen (URL):</label>
        <input type="text" name="Imagen" value="<?= isset($interprete) ? $interprete->Imagen : '' ?>">

        <button type="submit">Guardar</button>
    </form>
<?php require_once __DIR__ . '/../layout/footer.phtml'; ?>